"""Crear tablas desde cero

Revision ID: 0bc4c6a64ac3
Revises: 
Create Date: 2025-09-15 10:02:30.497490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bc4c6a64ac3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('imagen', sa.String(length=200), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_producto')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('contraseña', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email')
    )
    op.create_table('carrito',
    sa.Column('id_carrito', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_carrito')
    )
    op.create_table('facturas',
    sa.Column('id_factura', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_factura')
    )
    op.create_table('mascotas',
    sa.Column('id_mascota', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('especie', sa.String(length=50), nullable=False),
    sa.Column('raza', sa.String(length=50), nullable=True),
    sa.Column('genero', sa.String(length=10), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_mascota')
    )
    op.create_table('medicamentos',
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('dosis', sa.String(length=100), nullable=True),
    sa.Column('indicaciones', sa.Text(), nullable=True),
    sa.Column('contraindicaciones', sa.Text(), nullable=True),
    sa.Column('laboratorio', sa.String(length=100), nullable=True),
    sa.Column('registro_sanitario', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_producto'),
    sa.UniqueConstraint('registro_sanitario')
    )
    op.create_table('carrito_items',
    sa.Column('id_item', sa.Integer(), nullable=False),
    sa.Column('id_carrito', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_carrito'], ['carrito.id_carrito'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_item')
    )
    op.create_table('citas',
    sa.Column('id_cita', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('motivo', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('id_mascota', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_veterinario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_mascota'], ['mascotas.id_mascota'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_veterinario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_cita'),
    sa.UniqueConstraint('fecha', 'hora', name='_fecha_hora_uc')
    )
    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.create_index('ix_cita_fecha', ['fecha'], unique=False)

    op.create_table('detalles_factura',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('id_factura', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_factura'], ['facturas.id_factura'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    op.create_table('historias_clinicas',
    sa.Column('id_historia', sa.Integer(), nullable=False),
    sa.Column('id_mascota', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('tratamiento', sa.Text(), nullable=True),
    sa.Column('diagnostico', sa.Text(), nullable=True),
    sa.Column('id_cita', sa.Integer(), nullable=True),
    sa.Column('id_veterinario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cita'], ['citas.id_cita'], ),
    sa.ForeignKeyConstraint(['id_mascota'], ['mascotas.id_mascota'], ),
    sa.ForeignKeyConstraint(['id_veterinario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_historia')
    )
    op.create_table('recetas',
    sa.Column('id_receta', sa.Integer(), nullable=False),
    sa.Column('id_historia', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_historia'], ['historias_clinicas.id_historia'], ),
    sa.PrimaryKeyConstraint('id_receta')
    )
    op.create_table('receta_medicamento',
    sa.Column('id_receta_medicamento', sa.Integer(), nullable=False),
    sa.Column('id_receta', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_historia', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('indicaciones', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_historia'], ['historias_clinicas.id_historia'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.ForeignKeyConstraint(['id_receta'], ['recetas.id_receta'], ),
    sa.PrimaryKeyConstraint('id_receta_medicamento')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receta_medicamento')
    op.drop_table('recetas')
    op.drop_table('historias_clinicas')
    op.drop_table('detalles_factura')
    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.drop_index('ix_cita_fecha')

    op.drop_table('citas')
    op.drop_table('carrito_items')
    op.drop_table('medicamentos')
    op.drop_table('mascotas')
    op.drop_table('facturas')
    op.drop_table('carrito')
    op.drop_table('usuarios')
    op.drop_table('productos')
    # ### end Alembic commands ###
