"""Añadir observaciones a historia_clinica

Revision ID: 1e5689a4041e
Revises: 0bc4c6a64ac3
Create Date: 2025-09-17 14:10:56.028923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e5689a4041e'
down_revision = '0bc4c6a64ac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historias_clinicas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observaciones', sa.Text(), nullable=True))

    with op.batch_alter_table('receta_medicamento', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_historia')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receta_medicamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_historia', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'historias_clinicas', ['id_historia'], ['id_historia'])

    with op.batch_alter_table('historias_clinicas', schema=None) as batch_op:
        batch_op.drop_column('observaciones')

    # ### end Alembic commands ###
