"""Añadir campos de cliente a factura

Revision ID: 37b29b3886c2
Revises: 1e5689a4041e
Create Date: 2025-09-30 17:31:35.953200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37b29b3886c2'
down_revision = '1e5689a4041e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_cliente', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('email_cliente', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('direccion_envio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('telefono_cliente', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('metodo_pago', sa.String(length=50), nullable=True))

    with op.batch_alter_table('medicamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicamentos', schema=None) as batch_op:
        batch_op.drop_column('stock')

    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.drop_column('metodo_pago')
        batch_op.drop_column('telefono_cliente')
        batch_op.drop_column('direccion_envio')
        batch_op.drop_column('email_cliente')
        batch_op.drop_column('nombre_cliente')

    # ### end Alembic commands ###
