"""estructura inicial limpia

Revision ID: f0ee89fc8740
Revises: 
Create Date: 2025-09-05 11:35:38.171551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0ee89fc8740'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('contraseña', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email')
    )
    op.create_table('carrito',
    sa.Column('id_carrito', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_carrito')
    )
    op.create_table('mascotas',
    sa.Column('id_mascota', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('especie', sa.String(length=50), nullable=False),
    sa.Column('raza', sa.String(length=50), nullable=True),
    sa.Column('genero', sa.String(length=10), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_mascota')
    )
    op.create_table('citas',
    sa.Column('id_cita', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('id_mascota', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_mascota'], ['mascotas.id_mascota'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_cita'),
    sa.UniqueConstraint('fecha', 'hora', name='_fecha_hora_uc')
    )
    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.create_index('ix_cita_fecha', ['fecha'], unique=False)

    op.create_table('historia_clinica',
    sa.Column('id_historia', sa.Integer(), nullable=False),
    sa.Column('id_mascota', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('tratamiento', sa.Text(), nullable=True),
    sa.Column('diagnostico', sa.Text(), nullable=True),
    sa.Column('id_cita', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cita'], ['citas.id_cita'], ),
    sa.ForeignKeyConstraint(['id_mascota'], ['mascotas.id_mascota'], ),
    sa.PrimaryKeyConstraint('id_historia')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historia_clinica')
    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.drop_index('ix_cita_fecha')

    op.drop_table('citas')
    op.drop_table('mascotas')
    op.drop_table('carrito')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
